# Generated by Django 5.0.6 on 2024-06-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blocked_user",
            field=models.ManyToManyField(
                blank=True, related_name="user_blocked", to="social.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="user_followers", to="social.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="user_following", to="social.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="panding_request",
            field=models.ManyToManyField(
                blank=True, related_name="pandingRequest", to="social.userprofile"
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
