# Generated by Django 5.0.6 on 2024-06-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_userprofile_blocked_user_userprofile_followers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="private_account",
            field=models.BooleanField(default=False),
        ),
    ]
