# Generated by Django 5.0.6 on 2024-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_remove_userprofile_blocked_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="user_followers", to="social.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="user_following", to="social.userprofile"
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
