# Generated by Django 5.0.6 on 2024-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_post_likes_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
