# Generated by Django 5.0.6 on 2024-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0013_alter_like_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="action",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike")],
                default=1,
                max_length=7,
            ),
            preserve_default=False,
        ),
    ]
