# Generated by Django 5.0.6 on 2024-07-03 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0014_like_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="user_followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="user_following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
