# Generated by Django 5.0.6 on 2024-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0015_alter_userprofile_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="user_followers", to="social.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="user_following", to="social.userprofile"
            ),
        ),
    ]
