# Generated by Django 5.0.6 on 2024-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0017_alter_post_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
