# Generated by Django 5.0.6 on 2024-07-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0019_post_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateField(),
        ),
    ]
